version: "3.8"

services:
  postgres:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend/ExpenseTracker.API
    ports:
      - "5000:80"
    depends_on:
      - postgres

  frontend:
    build: ./frontend/expense-tracker-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata:
